[package]
name = "python_plugins"
version = "0.1.0"
edition = "2024"



[dependencies]
pyo3 = { version = "0.27" , features = ["auto-initialize", "abi3-py37"]}
pyo3-async-runtimes = { version = "0.27", features = ["attributes", "tokio-runtime"] }
models = {path = "../models"}
zip-extract = { version = "0.4.1" }
#ruff_python_parser = { git = "https://github.com/astral-sh/ruff", package = "ruff_python_parser" }
#ruff_linter = { git = "https://github.com/astral-sh/ruff", package = "ruff_linter" }
