[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true, features = ["multipart"] }
tokio = { workspace = true }
models = {workspace = true}
serde = {workspace = true}
python_plugins={workspace = true}

tower-http = { version = "0.6.8", features = ["cors", "fs"] }
tower = "0.5.2"
async_zip = { version = "0.0.18", features = ["full"] }
