[package]
name = "models"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
serde_json = {workspace = true}
pyo3 = { workspace = true }
tokio = { workspace = true }

rand = { version = "0.10.0-rc.6" }
parking_lot = { version = "0.12.5", features = ["nightly", "serde"] }